In [1]:
import pandas as pd

# Dataset import

In [2]:
diamonds = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv')

# Practice test

1. Read CSV and Print First 5 Rows
2. Modify Default Column Values and Print First 6 Rows
3. Select a Series from Diamonds DataFrame
4. Create a New 'Quality -color' Series
5. Count Rows, Columns, and Data Types
6. Summarize Only 'Object' Columns
7. Rename Two Columns
8. Rename All Columns
9. Remove the Second Column
10. Remove Multiple Columns at Once
11. Sort the 'cut' Series in Ascending Order

In [11]:
diamonds.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [22]:
print('Next answer 2')
print(diamonds[['carat','cut','color','x','y','z']].head())

print('Next answer 3')
print(diamonds.loc[1,'x'])

print('Next answer 4')
diamonds['Quality -color'] = None
print(diamonds.head(1))

print('Next answer 5')
print(diamonds.shape)
print(diamonds.dtypes)

print('Next answer 6')
print(diamonds.describe(include='object'))

print('Next answer 7')
print(diamonds.rename(columns={'cut':'cut2','x':'x1'}).head(1))

print('Next answer 8')
print(diamonds.rename(columns={'cut':'cut2','x':'x1','y':'y1'}).head(1))


print('Next answer 9')
print(diamonds.drop('cut',axis=1).head(1))

print('Next answer 10')
print(diamonds.drop(['cut','color'],axis=1).head(1))

print('Next answer 11')
print(diamonds['cut'].sort_values(ascending).head(2))

Next answer 2
   carat      cut color     x     y     z
0   0.23    Ideal     E  3.95  3.98  2.43
1   0.21  Premium     E  3.89  3.84  2.31
2   0.23     Good     E  4.05  4.07  2.31
3   0.29  Premium     I  4.20  4.23  2.63
4   0.31     Good     J  4.34  4.35  2.75
Next answer 3
3.89
Next answer 4
   carat    cut color clarity  depth  table  price     x     y     z  \
0   0.23  Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43

  Quality -color
0           None
Next answer 5
(53940, 11)
carat             float64
cut                object
color              object
clarity            object
depth             float64
table             float64
price               int64
x                 float64
y                 float64
z                 float64
Quality -color     object
dtype: object
Next answer 6
          cut  color clarity Quality -color
count   53940  53940   53940              0
unique      5      7       8              0
top     Ideal      G     SI1            NaN
freq    21551  11292   13065            NaN
Next answer 7
   carat   cut2 color clarity  depth  table  price    x1     y     z  \
0   0.23  Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43

  Quality -color
0           None
Next answer 8
   carat   cut2 color clarity  depth  table  price    x1    y1     z  \
0   0.23  Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43

  Quality -color
0           None
Next answer 9
   carat color clarity  depth  table  price     x     y     z Quality -color
0   0.23     E     SI2   61.5   55.0    326  3.95  3.98  2.43           None
Next answer 10
   carat clarity  depth  table  price     x     y     z Quality -color
0   0.23     SI2   61.5   55.0    326  3.95  3.98  2.43           None
Next answer 11
8748     Very Good
23064    Very Good
Name: cut, dtype: object

# 2nd test
# Titanic Pandas Practice Challenge (20 Questions)

# 🧱 Section 1: Basic Data Exploration

1. Display the first 10 rows of the dataset.

2. Show the total number of rows and columns.

3. Display all column names.

4. Show data types of each column.

5. How many missing values does each column have?

In [3]:
import seaborn as sns
titanic = sns.load_dataset('titanic')

In [23]:
titanic.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [25]:

print('Next answer 2')
print(titanic.shape)

print('Next answer 3')
print(titanic.columns)

print('Next answer 4')
print(titanic.dtypes)


print('Next answer 5')
print(titanic.isnull().sum())

Next answer 2
(891, 15)
Next answer 3
Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')
Next answer 4
survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object
Next answer 5
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

# 🧹 Section 2: Data Cleaning

6. Drop rows where the age column is missing.

7. Fill missing embarked values with 'S'.

8. Convert the sex column into numeric form (e.g., male → 0, female → 1).

9. Check for duplicate rows and remove them.

10. Change the datatype of fare to integer (rounded down).

In [32]:
# titanic.drop(df['age']== 
# print(titanic.loc[titanic['age'].isnull() == False,].head()) or
print(titanic.dropna(subset=['age']).head(1))

print('Next answer 7')
print(titanic['embarked'].fillna('S').head(1))

print('Next answer 8')
print(titanic['sex'].map(dict(male=0,female=1)).head(1))

print('Next answer 9')
print(titanic.drop_duplicates().head(2))

print('Next answer 10')
print(titanic['fare'].astype(int).head(2))

   survived  pclass   sex   age  sibsp  parch  fare embarked  class  who  \
0         0       3  male  22.0      1      0  7.25        S  Third  man

   adult_male deck  embark_town alive  alone
0        True  NaN  Southampton    no  False
Next answer 7
0    S
Name: embarked, dtype: object
Next answer 8
0    0
Name: sex, dtype: int64
Next answer 9
   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
Next answer 10
0     7
1    71
Name: fare, dtype: int64


# 📊 Section 3: Data Selection & Filtering

11. Select only the age, sex, and fare columns.

12. Show passengers who paid more than 100 for the fare.

13. Show passengers who are female and older than 30.

14. Retrieve the 5 youngest passengers.

15. Show all passengers from class = "First" who survived.

In [47]:
print(titanic[['age','sex','fare']].head(1))

print('Next answer 12')
print(titanic[ (titanic['fare'] > 100) ].head(2))

print('Next answer 13')
print(titanic[ (titanic['sex'] == 'female') & (titanic['age'] >30) ].head(2))


print('Next answer 14')
print(titanic.sort_values('age').head(5))

print('Next answer 15')
print(titanic[ (titanic['class'] == 'First') & (titanic['survived'] ==1) ].head(2))

    age   sex  fare
0  22.0  male  7.25
Next answer 12
    survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
27         0       1    male  19.0      3      2  263.0000        S  First
31         1       1  female   NaN      1      0  146.5208        C  First

      who  adult_male deck  embark_town alive  alone
27    man        True    C  Southampton    no  False
31  woman       False    B    Cherbourg   yes  False
Next answer 13
   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1         1       1  female  38.0      1      0  71.2833        C  First
3         1       1  female  35.0      1      0  53.1000        S  First

     who  adult_male deck  embark_town alive  alone
1  woman       False    C    Cherbourg   yes  False
3  woman       False    C  Southampton   yes  False
Next answer 14
     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
803         1       3    male  0.42      0      1   8.5167        C   Third
755         1       2    male  0.67      1      1  14.5000        S  Second
644         1       3  female  0.75      2      1  19.2583        C   Third
469         1       3  female  0.75      2      1  19.2583        C   Third
78          1       2    male  0.83      0      2  29.0000        S  Second

       who  adult_male deck  embark_town alive  alone
803  child       False  NaN    Cherbourg   yes  False
755  child       False  NaN  Southampton   yes  False
644  child       False  NaN    Cherbourg   yes  False
469  child       False  NaN    Cherbourg   yes  False
78   child       False  NaN  Southampton   yes  False
Next answer 15
   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1         1       1  female  38.0      1      0  71.2833        C  First
3         1       1  female  35.0      1      0  53.1000        S  First

     who  adult_male deck  embark_town alive  alone
1  woman       False    C    Cherbourg   yes  False
3  woman       False    C  Southampton   yes  False

# 📈 Section 4: Grouping & Aggregation

16. Calculate the average age by passenger class.

17. Find the total number of survivors in each class.

18. Show the average fare by embarked port.

19. Find the most common age in the dataset.

20.Find the average survival rate by gender.

In [48]:
titanic.head(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False

In [ ]:
print(titanic.groupby('class')['age'].mean())

print('Next answer 17')
print(titanic.groupby('class')['survived'].sum())


print('Next answer 18')
print(titanic.groupby('embarked')['fare'].mean())

print('Next answer 19')
# common = 
print(titanic['age'].value_counts().head(1))

print('Next answer 20')
print(titanic.groupby('sex')['survived'].mean())